name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}       
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export PATH=$PATH:/root/.nvm/versions/node/v24.14.0/bin

            echo "Node path loaded"

            which node
            which npm
            which pm2

            cd /var/www/fabnoor/Fabnoor-backend  

            git pull origin main

            npm install

            pm2 restart backend